{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.sample",
    "module": "lib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib-metadata-1.0.0.jar",
          "url": "lib-1.0.0.jar",
          "size": 2096,
          "sha512": "a74dbb33ef6fe9144163c681df187b91d51f7eb14f81364392d51ef394048bd5d6e234e353ee62fbe1a1d58d229c2fbe4fb65829343402284c5a3f5834d8896e",
          "sha256": "e5f74243f5d5a1ef9b6c4ac84edc348201f12f44618f6d08d5e15f5f7c0aa9e1",
          "sha1": "5bb8e21b145d83e072b9f38e5cfc5a30119877a5",
          "md5": "4bcf1510378eea2f226fa9defd1e345c"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "lib-kotlin-1.0.0-sources.jar",
          "url": "lib-1.0.0-sources.jar",
          "size": 925,
          "sha512": "fe06756a99b861679d523402263014129d5388eedcbc9aaeeda2fa640ab9d126bef2acae2111fd70fab26626155dec788ba53cac51b4aca4909e1054fc8e7478",
          "sha256": "cca2487fa3e10101db657f8f665e38c3c801a1197b6020f6365e903bc42e162c",
          "sha1": "794b1de51410b3450a7012ee92dc49e122dbe429",
          "md5": "e51e54d2402b25920b5c5bf9e20e0b1a"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lib-android/1.0.0/lib-android-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lib-android/1.0.0/lib-android-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../lib-android/1.0.0/lib-android-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-android",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/1.0.0/lib-jvm-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/1.0.0/lib-jvm-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../lib-jvm/1.0.0/lib-jvm-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-jvm",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-linuxx64/1.0.0/lib-linuxx64-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-linuxx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-linuxx64/1.0.0/lib-linuxx64-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-linuxx64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-macosarm64/1.0.0/lib-macosarm64-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-macosarm64/1.0.0/lib-macosarm64-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-macosarm64",
        "version": "1.0.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../lib-macosarm64/1.0.0/lib-macosarm64-1.0.0.module",
        "group": "org.jetbrains.sample",
        "module": "lib-macosarm64",
        "version": "1.0.0"
      }
    }
  ]
}
