{
  "formatVersion": "1.1",
  "component": {
    "url": "../../lib/1.0.0/lib-1.0.0.module",
    "group": "org.jetbrains.sample",
    "module": "lib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.20"
          }
        }
      ],
      "files": [
        {
          "name": "lib.klib",
          "url": "lib-linuxx64-1.0.0.klib",
          "size": 4046,
          "sha512": "9cb1d64290ace74561862c99f89ece04216012be62452641523ce991377c3b7a3724c556a83889f8daa1ab1d8d6dbc4dda46aea19eda9647c3903d012edded5b",
          "sha256": "70e6ec4eea5662aa94f7b58d9dd2c62c09acbd223b6e3cb8c320165f9871b3d2",
          "sha1": "badc22c1cfb34d8d510b71ed116c6e1a0bcf44a0",
          "md5": "ad4baaeeed05d111d2ecd3c618d8bad9"
        }
      ]
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "lib-linuxx64-1.0.0-sources.jar",
          "url": "lib-linuxx64-1.0.0-sources.jar",
          "size": 539,
          "sha512": "c17f8093f58b659f8959f173dcd889f44262f58cf56555afb906267a135567aac89c3526af5341d86eddbf2278e4c5a154a47402862a8018b128d765a701e017",
          "sha256": "f296253e2382e362e3f63c415c96184cf982f6118f6083f0aa5bab39fd70254d",
          "sha1": "e67d8a607ca959ba5427241ec2a13e4bd753288f",
          "md5": "8be9e938c853908d7323189427b8f727"
        }
      ]
    }
  ]
}
